<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>freepik__weight_scale_with__tmk__word.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ZeroWeightDetector.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="config.json" />
    <None Remove="Fonts\DS-DIGI.TTF" />
    <None Remove="Fonts\DS-DIGIB.TTF" />
    <None Remove="Fonts\DS-DIGII.TTF" />
    <None Remove="Fonts\DS-DIGIT.TTF" />
    <None Remove="freepik__weight_scale_with__tmk__word.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\DS-DIGI.TTF">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\DS-DIGIB.TTF">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\DS-DIGII.TTF">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\DS-DIGIT.TTF">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="freepik__weight_scale_with__tmk__word.ico" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="MainWindow.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Page>
  </ItemGroup>

</Project>
